//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporOrganizasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mekan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mekan()
        {
            this.Etkinlik = new HashSet<Etkinlik>();
        }
    
        public int Mid { get; set; }
        public string MekanAdi { get; set; }
        public Nullable<int> IlceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etkinlik> Etkinlik { get; set; }
        public virtual Ilceler Ilceler { get; set; }
    }
}
