//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporOrganizasyon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SporOEntities : DbContext
    {
        public SporOEntities()
            : base("name=SporOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etkinlik> Etkinlik { get; set; }
        public virtual DbSet<EtkinlikTipi> EtkinlikTipi { get; set; }
        public virtual DbSet<HataLoglari> HataLoglari { get; set; }
        public virtual DbSet<Ilceler> Ilceler { get; set; }
        public virtual DbSet<Iller> Iller { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Mekan> Mekan { get; set; }
        public virtual DbSet<Sporlar> Sporlar { get; set; }
    
        public virtual ObjectResult<EtkinlikAl_Result> EtkinlikAl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EtkinlikAl_Result>("EtkinlikAl");
        }
    
        public virtual int EtkinlikTarihKontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EtkinlikTarihKontrol");
        }
    
        public virtual int IsLoginUser(Nullable<int> kid)
        {
            var kidParameter = kid.HasValue ?
                new ObjectParameter("kid", kid) :
                new ObjectParameter("kid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IsLoginUser", kidParameter);
        }
    
        public virtual int KullaniciSporEkle(Nullable<int> kid, Nullable<int> sid)
        {
            var kidParameter = kid.HasValue ?
                new ObjectParameter("kid", kid) :
                new ObjectParameter("kid", typeof(int));
    
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KullaniciSporEkle", kidParameter, sidParameter);
        }
    
        public virtual int SonKullanici()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SonKullanici");
        }
    }
}
